# Generated by Django 5.0.4 on 2024-06-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_caseprofile_sanction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseprofile',
            name='apology_letter',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='community_service_deadline',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='community_service_hours',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='sanction',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='suspension_end_date',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='suspension_start_date',
        ),
        migrations.AddField(
            model_name='student',
            name='apology_letter',
            field=models.FileField(blank=True, null=True, upload_to='apology_letters/'),
        ),
        migrations.AddField(
            model_name='student',
            name='community_service_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='community_service_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sanction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='suspension_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='suspension_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
