# Generated by Django 5.0.4 on 2024-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_caseprofile_apology_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmoral',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sanction',
            field=models.CharField(blank=True, choices=[('apology_letter', 'Apology Letter'), ('community_service', 'Community Service'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CommunityServiceTracker',
        ),
    ]
